### ISSUE TITLE
グラフサンプル版コミットしたが、Herokuに反映されない

### ISSUE THREAD

**Issue by yoshinari21** [born-in-makuhari/titor#11]
申し訳ないが確認お願いです。和さん

**Comment by yoshinari21** [comment]
コミットもちゃんとされてるとおもうが。。。

**Comment by craftpaperbag** [comment]
@yoshinari21 をコラボレーターにするので、そこでビルドログ確認してみて

**Comment by yoshinari21** [comment]
コラボレータになれた～

**Comment by craftpaperbag** [comment]
治ったのでここはクローズ。
以下やったことメモ
1. 必要なパッケージをrequirements.txtに追加した
   - 追加方法をwikiに書いておきます。
   - requirements.txtを自動生成したいならvirtualenvを使うことになります。
2. heroku上ではstaticfilesと/static/を結びつけるよう設定
   - 古いけど参考：http://stackoverflow.com/questions/9047054/heroku-handling-static-files-in-django-app
   - herokuだと静的ファイルの置き場所がstaticfilesになる
   - ここの関係(herokuはSTATIC_ROOTに指定された場所を使う？)がまだ不明
3. heroku上ではALLOWED_HOSTSを*に指定
   - ここも要勉強。
   - ついでにherokuかどうかは、DEBUG==FalseじゃなくてPRODUCTION==Trueで判別するようにしました
