### ISSUE TITLE
django-chartjsではなくchart.jsにしたい

### ISSUE THREAD

**Issue by yoshinari21** [born-in-makuhari/titor#13]
django-chartjsはドキュメントあまりないため。
どうでしょう？

**Comment by yoshinari21** [comment]
でも基本的につかい方はいっしょなのかも

**Comment by yoshinari21** [comment]
使い方いっしょやね
もうちょうい調べてみて問題ないなら本件クローズ

**Comment by craftpaperbag** [comment]
いいと思う。最新のコミットが2015/11だし、そんなに活発じゃなさそうだし。

django-chartjs(pythonパッケージ)からchartjs(生のjs)に切り替えると、自分で静的ファイルを配置してviewで読み込む必要があると思うので、ブランチ切って切り替えまで対応しちゃおう

---

※一部嘘ついたんで修正しました；

**Comment by craftpaperbag** [comment]
ちなみにchartjsだけでローソク足は表現できるんだろうか？

**Comment by yoshinari21** [comment]
OK
じゃあchart.jsを使う方針で、作成してみる。（またちょっとデモ版つくるけど少し時間かかるかも）

ローソク足は難しそう。。。しらべてみる

**Comment by craftpaperbag** [comment]
:+1:

**Comment by yoshinari21** [comment]
完了　クローズ
