### ISSUE TITLE
python→jsに変数わたすところがうまくいかないー

### ISSUE THREAD

**Issue by yoshinari21** [born-in-makuhari/titor#15]
和さんヘルプ

**Comment by yoshinari21** [comment]
ブランチchartjs_editのviews.py139行目の30_day_registrationsがtemplates/titor/graph.htmlの19行目に渡されるんだけど、数値型じゃないと正常に渡されないんだよね。文字列の場合はjs側で返還が必要？

**Comment by craftpaperbag** [comment]
上のコメント見てくれ。多分これで解決する（吹き出しをクリックすれば見れる）

**Comment by yoshinari21** [comment]
クリア
シングルクォートを文字コードから置換→JSON文字列→オブジェクトに変換で解決

**Comment by yoshinari21** [comment]
本件クローズ
