### ISSUE TITLE
グラフを出す

### ISSUE THREAD

**Issue by craftpaperbag** [born-in-makuhari/titor#4]

**Comment by craftpaperbag** [comment]
グラフを出すところまで完了したら、

一旦masterにマージ＆pushお願いします。

（日経平均の表示は別ブランチで）

**Comment by yoshinari21** [comment]
まずは画面デモ版をmasterにマージします～

**Comment by yoshinari21** [comment]
ヒエッ　コンフリクト。。。

**Comment by craftpaperbag** [comment]
おつ！
（完了ならクローズしちゃってOKです）

![tumblr_n87y30paxa1re1y0eo1_500](https://cloud.githubusercontent.com/assets/3727665/16197298/818d4a6e-373c-11e6-9267-2e85923ebb40.gif)
